name: ipip-mbti-build-deploy

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Image Version'
        required: true
        default: 1.0.0
      targetRepo:
        description: 'Target Repo'
        required: true
        default: 'public'
        type: choice
        options:
        - public
        - private

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/kde-${{ inputs.targetRepo }}-repo:v${{ inputs.imageVersion }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
          file: ./mbti_ipip/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with: 
          app-name: 'kmlops-ipip-mbti-azure'
          images: ${{ env.IMAGE_NAME }}
      
      - name: Echo Results
        run: |
          echo 'input image version:  ${{ inputs.imageVersion }}'
          echo 'input image repo:  ${{ inputs.targetRepo }}'
          echo 'output URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}'

      - name: Azure logout
        run: |
          az logout